### ISSUE TITLE
Jitpack downtime

### ISSUE THREAD

**Issue by Sammy2005** [AfricasTalkingLtd/africastalking-java#17]
Kind offer an alternative to jitpack.io.
As at today it's been down for two days https://www.saashub.com/jitpack-status

**Comment by intothemoonlite** [comment]
@Sammy2005 did you another way to get the dependency from jitpack?

**Comment by Sammy2005** [comment]
Not really we considered moving yo a different provider die to the cost
implication on our business

**Comment by ericwathome** [comment]
also getting a 404 while syncing dependencies
