### ISSUE TITLE
Facing an issue when installing

### ISSUE THREAD

**Issue by KinyuaMwaniki** [AfricasTalkingLtd/africastalking-java#18]
I am trying to install this as a maven dependency using the instructions on the repo. I get this error

`Could not find artifact com.github.AfricasTalkingLtd.africastalking-java:core:pom:3.4.9 in jitpack.io (https://jitpack.io)
Could not find artifact com.github.AfricasTalkingLtd.africastalking-java:core:pom:3.4.9 in jitpack.io (https://jitpack.io)`

Can anyone provide any direction on this? I have tried it on Java 19 and on Java 11 with a previous version.

Thanks.

**Comment by aksalj** [comment]
Hey @KinyuaMwaniki, the version `3.4.9` was having issues publishing. Should be OK now!

**Comment by ericwathome** [comment]
same issue

**Comment by KinyuaMwaniki** [comment]
@ericwathome .

This is what I did.

1. Go to https://jitpack.io
2. Enter the URL to this repo.
3. Click get on the version you want.
