### ISSUE TITLE
Could Not Resolve Dependencies For Project

### ISSUE THREAD

**Issue by NabilTheNoise** [AfricasTalkingLtd/africastalking-java#20]
Hi. I was trying to add the `3.4.8` version to my java project using `maven` but I am facing this message:
` Could not find artifact com.github.AfricasTalkingLtd.africastalking-java:core:jar:3.4.8 in jitpack.io (https://jitpack.io) -> [Help 1]`

I had double checked with your documentation and also checked jitpack to see the status of your dependency, everything seems fine. But as I add it to my project and it starts downloading this version, it shows the above message. 

Can you help us? :)
Warmest regards

**Comment by aksalj** [comment]
Hey @NabilTheNoise,

Please try the latest version `3.4.9`.

**Comment by NabilTheNoise** [comment]
Thanks for your quick answer :))

**Comment by NabilTheNoise** [comment]
@aksalj 
sorry but I can't find the changelogs for these versions. Just wanted to make sure if I change the version, nothing will go wrong :)

**Comment by aksalj** [comment]
I see. If you really need `3.4.8` then try `:v3.4.8` instead of `:3.4.8`. See https://jitpack.io/#AfricasTalkingLtd/africastalking-java/v3.4.8
