### ISSUE TITLE
Artifact ID

### ISSUE THREAD

**Issue by theRealRizeo** [AfricasTalkingLtd/africastalking-java#4]
Hi,

Please change artifact id from `core` to `com.africastalking` . Using `core` is not good standards and its just good practice to name a dependency jar file the name of the package in the jar file

**Comment by aksalj** [comment]
Hi @theRealRizeo,

Seeing that the `artifactId` is used with the context of a `groupId`, which is correctly named `com.africastalking`, I think `core` or anything short makes sense. Consider this gradle example:

```
dependencies{
  implementation 'com.africastalking:core:3.4.2'
  // Or this
  implementation 'com.africastalking:com.africastalking:3.4.2'
}
```

Which of the two reads better?

**Comment by theRealRizeo** [comment]
Hi,

The issue with this is the jar file produced is called `core` which is bad naming convention. It should be the package name or the name of the project like `africastalking` for example, if you go to the maven repository you can see examples https://mvnrepository.com/search?q=core . Artifact id should be `africastalking-core` and not just core. So the jar file downloaded will be africastalking-core.jar and it will be more identifiable to anyone

**Comment by aksalj** [comment]
`africastalking-core` for artifact id is definitely better than the initial suggestion of `com.africastalking`
